spring:
  profiles:
    active: nonprod
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
---
spring:
  profiles: nonprod
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9095, localhost:9096, localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/Users/pkansal/Desktop/data/kafka/SSL/client.truststore.jks
        trust-store-password: prachi
        key-store-location: file:/Users/pkansal/Desktop/data/kafka/SSL/client.keystore.jks
        key-store-password: prachi
      properties:
        acks: all
        retries: 10
        lingerMs: 0
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer